//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfIntern.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountMaster()
        {
            this.Beneficiaries = new HashSet<Beneficiary>();
            this.TransTables = new HashSet<TransTable>();
        }
    
        public decimal AccNo { get; set; }
        public string AccHolder { get; set; }
        public string IFSCCode { get; set; }
        public string AccType { get; set; }
        public Nullable<System.DateTime> AccOpenDate { get; set; }
        public int AccBalance { get; set; }
        public string AccStatus { get; set; }
        public decimal CustId { get; set; }
    
        public virtual NewAcc NewAcc { get; set; }
        public virtual BranchTable BranchTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficiary> Beneficiaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransTable> TransTables { get; set; }
    }
}
