//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfIntern.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beneficiary()
        {
            this.TransTables = new HashSet<TransTable>();
        }
    
        public decimal AccNo { get; set; }
        public decimal BenAccNo { get; set; }
        public string BenName { get; set; }
        public string NickName { get; set; }
        public string BenBankName { get; set; }
        public string IFSCCode { get; set; }
        public decimal BeneficiaryID { get; set; }
        public string BeneficiaryType { get; set; }
        public string Remarks { get; set; }
    
        public virtual AccountMaster AccountMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransTable> TransTables { get; set; }
    }
}
