//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfIntern.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public decimal UserId { get; set; }
        public string Pwd { get; set; }
        public decimal CustId { get; set; }
    
        public virtual NewAcc NewAcc { get; set; }
        public string LoginErrorMsg { get; internal set; }
    }
}
