//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfIntern.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewAcc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewAcc()
        {
            this.AccountMasters = new HashSet<AccountMaster>();
            this.Logins = new HashSet<Login>();
        }
    
        public decimal CustId { get; set; }
        public string Title { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public decimal Phone { get; set; }
        public string Email { get; set; }
        public string PAN { get; set; }
        public decimal Aadhar { get; set; }
        public System.DateTime DOB { get; set; }
        public string ResAdd { get; set; }
        public string BranchName { get; set; }
        public string City { get; set; }
        public decimal Pincode { get; set; }
        public string State { get; set; }
        public string PerAdd { get; set; }
        public string PerAdd1 { get; set; }
        public string City01 { get; set; }
        public decimal pincode01 { get; set; }
        public string state01 { get; set; }
        public string Gender { get; set; }
        public string Occupation { get; set; }
        public decimal Income { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountMaster> AccountMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login> Logins { get; set; }
    }
}
