//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfIntern.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransTable
    {
        public Nullable<decimal> AccNo { get; set; }
        public Nullable<decimal> FromAccNo { get; set; }
        public Nullable<decimal> ToAccNo { get; set; }
        public Nullable<decimal> BeneficiaryID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<System.TimeSpan> TransTime { get; set; }
        public string TransType { get; set; }
        public decimal TransactionID { get; set; }
        public string Remarks { get; set; }
    
        public virtual AccountMaster AccountMaster { get; set; }
        public virtual Beneficiary Beneficiary { get; set; }
    }
}
